### ISSUE TITLE
Not executing :( Here is the issue.

### ISSUE THREAD

**Issue by bbettag21** [r00t-3xp10it/backdoorppt#10]
┌─[root@parrot]─[/home/user/backdoorppt]
└──╼ # ./backdoorppt.sh 

    +-+-+-+-+-+-+-+-+-+-+-+-+---+
    |b|a|c|k|d|o|o|r|p|p|t|:|1.7|
    +-+-+-+-+-+-+-+-+-+-+-+-+---+
    'Office spoof extensions tool'
    Credits: Damon Mohammadbagher

[☆] Checking backend applications .. 
[☆] Ruby installation   : found! 
[☆] Wine installation   : found! 
[☆] Zenity installation : found! 
[☆] Xterm installation  : found! 
[☆] Wine Program Files (x86)  : found! 
**[x] Aborting all tasks  : done!**

Codename::ghost-in-a-shell 
Author::pedr0 ubuntu::[r00t-3xp10it]
backdoorppt::v1.7::SuspiciousShellActivity©::RedTeam::2017
┌─[root@parrot]─[/home/user/backdoorppt]
└──╼ #

**Comment by r00t-3xp10it** [comment]
## possible reasons
1 - you have chosen to abort script execution ..
![bug 1](http://i.cubeupload.com/LLnLOm.png)
if you dont have pressed the 'yes' in the sandbox (zenity) then the script
execution will jump to the end, presenting that msg to user ..

2 - you did not provided all questions proper (script inputs)..
![bug 1](http://i.cubeupload.com/KrOU3h.png)

### recomendation:
my script reports that all dependencies are installed (backend appls)
so the only possible error that i see its not inputing the required settings or payload type ..

## check a video about this tool here ..
https://www.youtube.com/watch?v=k4UJW4p1E3w&t=24s
