### ISSUE TITLE
Resource Hacker

### ISSUE THREAD

**Issue by Nigrini** [r00t-3xp10it/backdoorppt#12]
Resource hacker is installed on my system, but is not detected. The program then "install" it again just to repeat the whole process the next time because it is not detecting resource hacker

Kali 2018.4 - (64)

**Comment by r00t-3xp10it** [comment]
<br />

- 1 - try to changes the next settings in backdoorppt.sh script
![pic](http://i65.tinypic.com/rbl7ih.png)
- 2 - save the script and try to install the dependencies again  ..

#### HINT: in Resource-Hacker.exe installer remmenber to chose Program Files (not Program Files (x86))
