### ISSUE TITLE
Does it opens a .PPT on the same time or not?

### ISSUE THREAD

**Issue by Vedant-Bhalgama** [r00t-3xp10it/backdoorppt#15]
We can bind the EXE with the .ppt and change the extension but when the Final Version is ran, does it opens PPT first and then does it run the actual EXE in Background?

**Comment by r00t-3xp10it** [comment]
yes we can do that ...
read **[this](https://gist.github.com/r00t-3xp10it/001fb01363e4b2b7ffab447cfe9090eb)** that i was planing on adding to venom new release ...
