### ISSUE TITLE
Directory Path issue 

### ISSUE THREAD

**Issue by ghost** [r00t-3xp10it/backdoorppt#5]
-e:1:in `rename': No such file or directory @ rb_file_s_rename - (backdoor_ppt.exe, resume‮tpp.exe) (Errno::ENOENT)
	from -e:1:in `<main>'

**Comment by r00t-3xp10it** [comment]
Issue 3 bug report discussion
[issue 3 github bug report from here](https://github.com/r00t-3xp10it/backdoorppt/issues/3)

backdoorppt under wine64 bits
[sicksecurity backdoorppt under wine64 bits](http://sicksec.gomezmarin.es/)

Or download the correction to the sourcecode (thanks to @4w4k3 bug report)
[4w4k3 sourcecode correction fix](https://github.com/r00t-3xp10it/backdoorppt)
