### ISSUE TITLE
debian too ?

### ISSUE THREAD

**Issue by sigmamale1980** [r00t-3xp10it/backdoorppt#8]
first off, thank you for a great script, using it on debian-testing but keep getting this :+1: 

![selection_003](https://cloud.githubusercontent.com/assets/8757525/26747668/1332fe8a-4800-11e7-89d6-dc7213eee351.png)

BTW .. wine ver is 32bit.
thx in adv.

**Comment by r00t-3xp10it** [comment]
if ..
your system its **64bits** why you are using **wine32** ??
`a) my script as looked at your arch, and configurated wine to 64bits use`
`b) for your screenshot i can see that exists folder **Program Files** <-- 32bits wine install`

### Quick fix ?

    1 - edit main script and change the next values to suite your needs

![fix](http://2.1m.yt/HcAgZqL.png)

**Comment by sigmamale1980** [comment]
wine32 enables me to test on 32bit systems
which is also compatible with 64bit os`s but not the other way around. 

i tried to remove the (x86) part from the script which continued to run ok
**but wont produce any payloads!**

any thoughts?
thx in adv.

**Comment by r00t-3xp10it** [comment]
yes ..
its not only the **PgFi=** variable that you need to change ..
you need to change **all this values** (to force my tool to use 32bits)..

    1 - dEd="x64"
    2 - arch="wine64"
    3 - PgFi="Program Files (x86)"
